from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class FailureCode(str, Enum):
    PHASE_TRANSITION_MISMATCH = "PHASE_TRANSITION_MISMATCH"
    COMMAND_GATE_FAILURE = "COMMAND_GATE_FAILURE"
    REVEAL_POLICY_VIOLATION = "REVEAL_POLICY_VIOLATION"
    VISIBILITY_LEAK = "VISIBILITY_LEAK"
    RULE_RESOLUTION_MISMATCH = "RULE_RESOLUTION_MISMATCH"
    SESSION_STATE_MISMATCH = "SESSION_STATE_MISMATCH"
    PERSISTENCE_RECOVERY_FAILURE = "PERSISTENCE_RECOVERY_FAILURE"
    STREAM_RECOVERY_FAILURE = "STREAM_RECOVERY_FAILURE"
    INTENT_ROUTING_MISMATCH = "INTENT_ROUTING_MISMATCH"
    NARRATION_CONTRACT_VIOLATION = "NARRATION_CONTRACT_VIOLATION"
    CONCURRENCY_INVARIANT_FAILURE = "CONCURRENCY_INVARIANT_FAILURE"
    SCENARIO_TIMEOUT = "SCENARIO_TIMEOUT"
    UNSUPPORTED_TEST_CONTRACT = "UNSUPPORTED_TEST_CONTRACT"
    ASSERTION_FAILED = "ASSERTION_FAILED"
    MISSING_STEP_FIELD = "MISSING_STEP_FIELD"
    UNKNOWN_STEP_TYPE = "UNKNOWN_STEP_TYPE"


@dataclass
class Failure:
    code: FailureCode
    message: str
    step_index: int
    expected: Any = None
    actual: Any = None
    artifact_pointer: str | None = None
